# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 11:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contact_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='me',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
