# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20170120_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='me',
            name='slug',
            field=models.SlugField(default='me', unique=True),
            preserve_default=False,
        ),
    ]
