# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_me_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='me',
            name='image',
            field=models.ImageField(upload_to='me'),
        ),
    ]
