# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0004_auto_20170127_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='image',
            field=models.ImageField(blank=True, upload_to='work-banner'),
        ),
    ]
